// main.c

#include "i2c.h"
#include "adc.h"
#include "fan_control.h"
#include "ti_msp_dl_config.h"

int main(void)
{
    // The SYSCFG_DL_init() function is generated by the TI SysConfig tool.
    // It is responsible for critical low-level setup including:
    // - Clock system initialization
    // - Power configuration
    // - Pin Muxing for all used peripherals (I2C_0, ADC_0, etc.)
    SYSCFG_DL_init();

    // Initialize our hardware abstraction layer modules.
    // These functions configure the peripherals for their specific roles in this application.
    I2c_Init();
    Adc_Init();

    // Initialize the application logic module.
    FanControl_Init();
    
    // Enable global interrupts. This allows the DMA IRQ to be processed by the CPU.
    __enable_irq();

    // The system is now fully interrupt-driven. The main loop simply enters a
    // low-power state, waiting for an interrupt to occur.
    while (1) {
        // __WFI() puts the CPU to sleep. It will wake up when the DMA
        // completes its transfer and fires the interrupt. The ISR will run,
        // and then execution will return here to go back to sleep.
        __WFI();
    }
}
